config/routes.rb
Rails.application.routes.draw do
  get 'api_instructions', to: 'home#api_instructions', defaults: { format: :html }
  devise_for :users
  resources :characters do
    resources :comments, only: [:destroy,:new,:index,:create], module: :characters
    collection do 
      post 'acquire_characters'
    end
  end
  resources :animals do
    resources :comments, only: [:destroy,:new,:index,:create], module: :animals
    collection do 
      post 'acquire_animals'
    end
  end
  resources :comments, only: [:show,:index,:destroy]
  devise_scope :user do
	  authenticated :user do
	    root 'characters#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :characters, except: [:edit,:new] do 
        collection do 
          post 'acquire_characters'
          get 'get_by_range'
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def api_instructions
  end
end

app/views/home/api_instructions.html.erb
  To use the api you must send the head <strong>X-API-KEY</strong> with the api key <strong>836ed3a72c75b1e2b06ca755adefd382f5faf3a 
  </strong>
<h3>Routes</h3>
  <h4>local routes</h4>
  
  - <strong>acquire_characters (post): </strong> http://localhost:3000/api/v1/characters/acquire_characters . To update characters from the api 
  <div class="col-md-3"></div>
  - <strong>get_by_range (get):</strong> http://localhost:3000/api/v1/characters/get_by_range . to get all character by range you must send
  parameter range (low_range, medium_range, high_range or ultra_range)
  <div class="col-md-3"></div>
  - <strong>index (get):</strong> http://localhost:3000/api/v1/characters/
  <div class="col-md-3"></div>
  - <strong>show (get):</strong> http://localhost:3000/api/v1/characters/1
  <div class="col-md-3"></div>
  - <strong>create (get):</strong> http://localhost:3000/api/v1/characters/
  <div class="col-md-3"></div>
  - <strong>update (put):</strong> http://localhost:3000/api/v1/characters/1
  <div class="col-md-3"></div>
  - <strong>destroy (delete):</strong> http://localhost:3000/api/v1/characters/1

  <h4>Production routes</h4>
  
  - <strong>acquire_characters (post):</strong> http://3.16.21.33/api/v1/characters/acquire_characters . To update characters from the api 
  <div class="col-md-3"></div>
  - <strong>get_by_range (get):</strong> http://3.16.21.33/api/v1/characters/get_by_range . to get all character by range you must send
  parameter range (low_range, medium_range, high_range or ultra_range)
  <div class="col-md-3"></div>
  - <strong>index (get):</strong> http://3.16.21.33/api/v1/characters/
  <div class="col-md-3"></div>
  - <strong>show (get): </strong>http://3.16.21.33/api/v1/characters/1
  <div class="col-md-3"></div>
  - <strong>create (get):</strong> http://3.16.21.33/api/v1/characters/
  <div class="col-md-3"></div>
  - <strong>update (put): </strong>http://3.16.21.33/api/v1/characters/1
  <div class="col-md-3"></div>
  - <strong>destroy (delete):</strong> http://3.16.21.33/api/v1/characters/1

<h2><%= link_to 'Back to log in', unauthenticated_root_path %></h2>