config/routes.rb
Rails.application.routes.draw do
  get 'api_instructions', to: 'home#api_instructions', defaults: { format: :html }
  devise_for :users
  resources :characters do
    resources :comments, only: [:destroy,:new,:index,:create], module: :characters
    collection do 
      post 'acquire_characters'
    end
  end
  resources :animals do
    resources :comments, only: [:destroy,:new,:index,:create], module: :animals
    collection do 
      post 'acquire_animals'
    end
  end
  resources :comments, only: [:show,:index,:destroy]
  devise_scope :user do
	  authenticated :user do
	    root 'characters#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :characters, except: [:edit,:new] do 
        collection do 
          post 'acquire_characters'
          get 'get_by_range'
        end
      end
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord

  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, presence: true
  validates_uniqueness_of :name


end

app/controllers/animals/comments_controller.rb
class Animals::CommentsController < CommentsController
  before_action :set_commentable


  def destroy
    @comment = Comment.find(params[:id])
    @comment = @comment.destroy
    respond_to do |format|
      if @comment.errors.present?
        puts ap @comment.errors.messages
        format.html { redirect_to animal_url(@commentable.id) }
        format.json { head :no_content }
      else
        format.html { redirect_to animal_url(@commentable.id)}
        format.json { head :no_content }
      end
    end
  end

  private
    def set_commentable
      @commentable = Animal.find(params[:animal_id])
    end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

  include ApplicationHelper
  
  before_action :set_animal, only: [:edit, :update,:show, :destroy]
  def index
    @animals = Animal.all 
    respond_to do |format|
      format.html
      format.json { render json: AnimalsDatatable.new(view_context, @animals) }
    end
  end

  def show 
  end

  def edit
  end
  
  def create
    @animal = Animal.new(animal_params)
    respond_to do |format|
      if @animal.save
        format.html { redirect_to animals_path }
      else
        format.html { render :new }
      end
    end
  end
  
  def new
    @animal = Animal.new
  end
  
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_path }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @animal = @animal.destroy 
    respond_to do |format|
      if @animal.errors.present?
        puts ap @animal.errors.messages
        format.html { redirect_to animals_url }
        format.json { head :no_content }
      else
        format.html { redirect_to animals_url}
        format.json { head :no_content }
      end
    end
  end
  
  def acquire_animals
    get_animal_data
    respond_to do |format|
      format.html { redirect_to animals_path }
    end
  end

  private
  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal)
          .permit(:name, :diet, :status)
  end

end

app/views/animals/_form.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= f.input :name, input_html: { class: 'form-control' }, label: false , required: true%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">diet</label>
  <div class="col-sm-8">
  <%= f.input :diet, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">status</label>
  <div class="col-sm-8">
  <%= f.input :status, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-sm" %>
  <%= link_to 'Back', animals_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/animals/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit animal</h1>
    <%= simple_form_for([@animal], wrapper: false, label: false, :method => :PATCH ) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/animals/index.html.erb
<div class="row">
  <h1>All animals</h1>
</div>
<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger pull-left" %>
<%= link_to 'Create animal', new_animal_path ,class: "btn btn-success pull-left" %>
<%= link_to 'Get All animals', acquire_animals_animals_path ,class: "btn btn-info pull-left", method: :post %>



<table class="table table-title" id="animals_datatable" data-source="<%= animals_path(format: "json") %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Diet</th>
        <th>Status</th>
        <th>Created at</th>
        <th style="width: 300px;"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/animals/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New animal</h1>
    <%= simple_form_for([@animal], wrapper: false, label: false) do |f| %>
      <%= render 'form' , f: f %>
    <% end %>
  </div>
</div>

app/views/animals/show.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= @animal.name%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">diet</label>
  <div class="col-sm-8">
  <%= @animal.diet%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">status</label>
  <div class="col-sm-8">
  <%= @animal.status %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">created_at date</label>
  <%= !@animal.created_at.nil? ? @animal.created_at.strftime("%d-%m-%y") : 'Doesnt have' %>
</div>

<%= render partial: "comments/comments", locals: {commentable: @animal} %>
<%= render partial: "comments/form", locals: {commentable: @animal} %>
<%= link_to 'Back', animals_path, class: "btn btn-primary btn-sm" %>