config/routes.rb
Rails.application.routes.draw do
  get 'api_instructions', to: 'home#api_instructions', defaults: { format: :html }
  devise_for :users
  resources :characters do
    resources :comments, only: [:destroy,:new,:index,:create], module: :characters
    collection do 
      post 'acquire_characters'
    end
  end
  resources :animals do
    resources :comments, only: [:destroy,:new,:index,:create], module: :animals
    collection do 
      post 'acquire_animals'
    end
  end
  resources :comments, only: [:show,:index,:destroy]
  devise_scope :user do
	  authenticated :user do
	    root 'characters#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :characters, except: [:edit,:new] do 
        collection do 
          post 'acquire_characters'
          get 'get_by_range'
        end
      end
    end
  end
end

app/models/character.rb
class Character < ApplicationRecord

  has_many :comments, as: :commentable, dependent: :destroy

  enum rank_range: [:low_range, :medium_range, :high_range, :ultra_range]

  validates :name, presence: true
  validates_uniqueness_of :name

  after_create :assing_range

  scope :get_rank_range, ->(range) {
    Character.where(rank_range: range)
  }


  def assing_range
    if rank.to_i < 50 
      self.rank_range = 0
    elsif rank.to_i < 100
      self.rank_range = 1
    elsif rank.to_i < 150
      self.rank_range = 2
    else 
      self.rank_range = 3  
    end
    self.save!
  end

end

app/controllers/api/v1/characters_controller.rb
module Api
  module V1
    class CharactersController < V1Controller

      before_action :set_character, only: [:show, :update, :destroy]

      include ApplicationHelper

      def index
        render json: { status: :ok, characters: Character.all}
      end

      def show
        render json: { status: :ok, character: @character}
      end
      
      def create
    		@character = Character.new(character_params)
        if @character.save
          render json: { status: :ok, character: @character}
        else
          render json: { status: :bad_request}
        end
      end
      
      def update
        @character.assign_attributes(character_params)
        if @character.save
          render json: { status: :accepted, character: @character}
        else
          render json: { status: :bad_request}
        end
      end

      def destroy
        if @character != nil && @character.destroy
          render json: { status: :ok}
        else
          render json: { status: :bad_request}
        end
      end

      def acquire_characters
        get_data_json
        render json: { status: :ok }
      end

      def get_by_range
        characters = Character.get_rank_range(params[:range]) 
        if characters.size > 0
          render json: { status: :ok, characters: characters }
        else
          render json: { status: :bad_request }
        end
      end
      
      private 

      def set_character
        @character = Character.where( id: params[:id]).last
      end
      
      def character_params
        params.require(:character)
              .permit(:name, :gender, :slug, :rank, :house)
      end
    end
  end
end

app/controllers/characters/comments_controller.rb
class Characters::CommentsController < CommentsController
  before_action :set_commentable


  def destroy
    @comment = Comment.find(params[:id])
    @comment = @comment.destroy
    respond_to do |format|
      if @comment.errors.present?
        puts ap @comment.errors.messages
        format.html { redirect_to character_url(@commentable.id) }
        format.json { head :no_content }
      else
        format.html { redirect_to character_url(@commentable.id)}
        format.json { head :no_content }
      end
    end
  end

  private
    def set_commentable
      @commentable = Character.find(params[:character_id])
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  include ApplicationHelper
  
  before_action :set_character, only: [:edit, :update,:show, :destroy]
  def index
    @characters = Character.all 
    respond_to do |format|
      format.html
      format.json { render json: CharactersDatatable.new(view_context, @characters) }
    end
  end

  def show 
  end

  def edit
  end
  
  def create
    @character = Character.new(character_params)
    respond_to do |format|
      if @character.save
        format.html { redirect_to characters_path }
      else
        format.html { render :new }
      end
    end
  end
  
  def new
    @character = Character.new
  end
  
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to character_path }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @character = @character.destroy 
    respond_to do |format|
      if @character.errors.present?
        puts ap @character.errors.messages
        format.html { redirect_to characters_url }
        format.json { head :no_content }
      else
        format.html { redirect_to characters_url}
        format.json { head :no_content }
      end
    end
  end
  
  def acquire_characters
    get_data_json
    respond_to do |format|
      format.html { redirect_to characters_path }
    end
  end

  private
  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character)
          .permit(:name, :gender, :slug, :rank, :house)
  end

end

app/views/characters/_form.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= f.input :name, input_html: { class: 'form-control' }, label: false , required: true%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">slug</label>
  <div class="col-sm-8">
  <%= f.input :slug, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">Gender</label>
  <div class="col-sm-8">
    <%= select_tag 'gender', options_for_select( ['Male', 'Female'] ), label: false, required: false %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">rank</label>
  <div class="col-sm-8">
  <%= f.input :rank, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">house</label>
  <div class="col-sm-8">
  <%= f.input :house, input_html: { class: 'form-control' }, label: false , required: false%>
  </div>
</div>
<div class="form-actions">
  <%= f.button :submit, class: "btn btn-success btn-sm" %>
  <%= link_to 'Back', characters_path, class: "btn btn-primary btn-sm" %>
</div>

app/views/characters/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>Edit character</h1>
    <%= simple_form_for([@character], wrapper: false, label: false, :method => :PATCH ) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<div class="row">
  <h1>All characters</h1>
</div>
<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-danger pull-left" %>
<%= link_to 'Create Character', new_character_path ,class: "btn btn-success pull-left" %>
<%= link_to 'Get All Characters', acquire_characters_characters_path ,class: "btn btn-info pull-left", method: :post %>



<table class="table table-title" id="characters_datatable" data-source="<%= characters_path(format: "json") %>">
    <thead>
      <tr>
        <th>Name</th>
        <th>Gender</th>
        <th>Slug</th>
        <th>Rank</th>
        <th>Rank range</th>
        <th>House</th>
        <th>Created at</th>
        <th>Have image?</th>
        <th style="width: 300px;"></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
</table>

app/views/characters/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1>New character</h1>
    <%= simple_form_for([@character], wrapper: false, label: false) do |f| %>
      <%= render 'form' , f: f %>
    <% end %>
  </div>
</div>

app/views/characters/show.html.erb
<div class="form-group">
  <label class="col-sm-4 control-label">Name</label>
  <div class="col-sm-8">
  <%= @character.name%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">gender</label>
  <div class="col-sm-8">
  <%= @character.gender%>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">slug</label>
  <div class="col-sm-8">
  <%= @character.slug %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">rank</label>
  <div class="col-sm-8">
  <%= @character.rank %>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-4 control-label">house</label>
  <div class="col-sm-8">
  <%= @character.house %>
  </div>
</div>
<%  if @character.image_url != nil %>
  <%= image_tag @character.image_url %>
<% end %>

<div class="form-group">
  <label class="col-sm-4 control-label">created_at date</label>
  <%= !@character.created_at.nil? ? @character.created_at.strftime("%d-%m-%y") : 'Doesnt have' %>
</div>

<%= render partial: "comments/comments", locals: {commentable: @character} %>
<%= render partial: "comments/form", locals: {commentable: @character} %>
  <%= link_to 'Back', characters_path, class: "btn btn-primary btn-sm" %>