config/routes.rb
Rails.application.routes.draw do
  get 'api_instructions', to: 'home#api_instructions', defaults: { format: :html }
  devise_for :users
  resources :characters do
    resources :comments, only: [:destroy,:new,:index,:create], module: :characters
    collection do 
      post 'acquire_characters'
    end
  end
  resources :animals do
    resources :comments, only: [:destroy,:new,:index,:create], module: :animals
    collection do 
      post 'acquire_animals'
    end
  end
  resources :comments, only: [:show,:index,:destroy]
  devise_scope :user do
	  authenticated :user do
	    root 'characters#index', as: :authenticated_root
	  end
		unauthenticated do
	   root "devise/sessions#new", as: :unauthenticated_root
	  end
  end
  ## API
  namespace :api , defaults: { format: 'json' } do
    namespace :v1 do
      resources :characters, except: [:edit,:new] do 
        collection do 
          post 'acquire_characters'
          get 'get_by_range'
        end
      end
    end
  end
end

app/views/layouts/_sidenav.html.erb
<div id="mySidenav" class="sidenav">
  <%= link_to 'Characters',characters_path %>
  <%= link_to 'Animals',animals_path %>
  <%= link_to 'Comments',comments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tachtech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main">
      <% if !current_user.nil? %>
        <%= render "layouts/sidenav" %>
      <% else %>
        <h3><%= link_to 'Api Instructions', api_instructions_path %></h3>
        
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>